"""empty message

Revision ID: 47e6f2890c82
Revises: edcee22b9488
Create Date: 2025-08-16 11:08:39.047330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e6f2890c82'
down_revision = 'edcee22b9488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('rarity', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('rarity')
        batch_op.drop_column('type')
        batch_op.drop_column('imageUrl')

    # ### end Alembic commands ###
