"""empty message

Revision ID: 56bffb958496
Revises: 8878f0ec5178
Create Date: 2025-07-30 15:49:58.748223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bffb958496'
down_revision = '8878f0ec5178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.drop_column('nombre')
        batch_op.drop_column('direccion_envio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_envio', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
