"""empty message

Revision ID: 633bd1dc6c2a
Revises: 1f1b830e272c
Create Date: 2025-08-03 19:23:02.914063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633bd1dc6c2a'
down_revision = '1f1b830e272c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
