"""empty message

Revision ID: 9b983c3fae47
Revises: 47e6f2890c82
Create Date: 2025-08-16 12:01:02.976856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b983c3fae47'
down_revision = '47e6f2890c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               nullable=False)
        batch_op.alter_column('rarity',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('rarity',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
