"""empty message

Revision ID: af0ef0333c2a
Revises: 0763d677d453
Create Date: 2025-07-28 13:28:26.395600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0ef0333c2a'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_single',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria')
    )
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('categoria_producto_single',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.String(length=120), nullable=False),
    sa.Column('categoria_id', sa.String(), nullable=False),
    sa.Column('rareza', sa.String(), nullable=False),
    sa.Column('categoria_single_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_single_id'], ['categoria_single.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio', sa.String(), nullable=False),
    sa.Column('stock', sa.String(), nullable=False),
    sa.Column('vendedor_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('categoria_producto_single')
    op.drop_table('vendedor')
    op.drop_table('categoria_single')
    # ### end Alembic commands ###
