"""empty message

Revision ID: c602e80eb6ed
Revises: 633bd1dc6c2a
Create Date: 2025-08-06 16:15:32.403398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c602e80eb6ed'
down_revision = '633bd1dc6c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['comprador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('admin_correo_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('correo')
        batch_op.drop_column('username')

    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprador_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['comprador_id'])
        batch_op.drop_constraint('carrito_id_comprador_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprador', ['comprador_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('id_comprador')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('comprador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('comprador_correo_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('correo')
        batch_op.drop_column('username')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])

    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('vendedor_correo_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('correo')
        batch_op.drop_column('username')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('vendedor_correo_key', ['correo'])
        batch_op.drop_column('email')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('comprador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('comprador_correo_key', ['correo'])
        batch_op.drop_column('email')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre')

    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_comprador', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('carrito_id_comprador_fkey', 'comprador', ['id_comprador'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('comprador_id')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('admin_correo_key', ['correo'])
        batch_op.drop_column('email')
        batch_op.drop_column('nombre')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
