"""empty message

Revision ID: edcee22b9488
Revises: b54ef7ad4b26
Create Date: 2025-08-11 18:45:42.985305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcee22b9488'
down_revision = 'b54ef7ad4b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
